exclude: 'docs|node_modules|migrations|.tox|.idea|venv|.serverless'
default_stages: [ commit ]
fail_fast: true

repos:
  # remote -----------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      # Security
      - id: detect-aws-credentials
      - id: detect-private-key
      # Detector
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      # Formatter
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Python code formatter
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [ "--line-length", "119" ]
        language_version: python3.8

  # sort imports alphabetically, and automatically separated into sections and by type
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ "-l", "119", "--profile", "black" ]
        language_version: python3.8

  # compliance to PEP8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args: [ "--config", "setup.cfg" ]
        additional_dependencies:
          - flake8-isort
          - flake8-black>=0.1.1
        language_version: python3.8

  # static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy

  # security
  - repo: https://github.com/PyCQA/bandit
    rev: 44f5c416cc0b7d62ca55b78e90bd1f7ee3d16082
    hooks:
      - id: bandit
        args: [ "-x", "venv,tests", "-r", "src" ]

  # local --------------------------------------------------
  - repo: local
    hooks:
      - id: git-check-commit-msg
        name: GIT check commit message
        language: pygrep
        entry: '\A(?!\[[0-9]+\])'
        args: [ --multiline ]
        stages: [ commit-msg ]
