ECRRepository:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: ${self:service}-${self:provider.stage}
    RepositoryPolicyText:
      Version: "2012-10-17"
      Statement:
        - Sid: AllowPushPull
          Effect: Allow
          Principal: "*" # TODO restric
          Action:
            - ecr:*
    LifecyclePolicy:
      LifecyclePolicyText: |
        {
          "rules": [
              {
                  "rulePriority": 1,
                  "description": "Delete untagged images",
                  "selection": {
                      "tagStatus": "untagged",
                      "countType": "sinceImagePushed",
                      "countUnit": "days",
                      "countNumber": 1
                  },
                  "action": {
                      "type": "expire"
                  }
              },
              {
                  "rulePriority": 2,
                  "description": "Delete expired images",
                  "selection": {
                      "tagStatus": "any",
                      "countType": "imageCountMoreThan",
                      "countNumber": 10
                  },
                  "action": {
                      "type": "expire"
                  }
              }
          ]
        }
