BridgeAppTopic:
  Type: AWS::SNS::Topic
  Properties:
    TopicName: ${self:service}-${self:provider.stage}-BridgeApp


BridgeAppSubscription:
  Type: AWS::SNS::Subscription
  Properties:
    Protocol: sqs
    Endpoint: !GetAtt BridgeAppQueue.Arn
    TopicArn: !Ref BridgeAppTopic
    RawMessageDelivery: 'true'


BridgeAppTopicPolicy:
  Type: AWS::SNS::TopicPolicy
  Properties:
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Sid: SnsTopicPolicy
          Effect: Allow
          Principal: '*'
          Action:
            - sns:Publish
            - sns:Subscribe
          Resource: !Ref BridgeAppTopic
    Topics:
      - !Ref BridgeAppTopic
