exclude: 'docs|node_modules|migrations|.tox|.idea'
default_stages: [commit]
fail_fast: true

repos:
  # Security
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: detect-aws-credentials
      - id: detect-private-key

  # formatter
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
