name: auto-release

on:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v5
      with:
        publish: true
        prerelease: false
        config-name: release-drafter.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
