name: Plan tests

on:
  pull_request:
    branches:
      - main
     
jobs:
  tests:
    name: Plan tests
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: terraform-compliance/github_action@main
      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Check AWS identity
        run: aws sts get-caller-identity
      - name: Check Terraform version
        uses: dflook/terraform-version@v1.12.0
        id: terraform-version
        with:
          path: '.'
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Plan for tests
        uses: dflook/terraform-plan@v1.17.2
        id: test-infra
        with:
          path: examples/complete
          variables: |
            deployment_id = "ci-${{ steps.vars.outputs.sha_short }}"
      - name: Put plan into output
        id:  plan_output
        run: |
          cp ${{ steps.test-infra.outputs.json_plan_path }} /tmp/plan.json
      - uses: actions/checkout@master
        with:
          repository: cerebral-inc/cerebral-terraform-compliance
          fetch-depth: 0
          ssh-key: ${{ secrets.TF_MODULES_READONLY_SSH_PRIVATE_KEY }}
      - name: terraform-compliance
        id: terraform-compliance-run
        run: |
          terraform-compliance -p /tmp/plan.json -f .
