name: Code Quality and Functionality Tests
on:
  pull_request:
    branches:
      - main
      - develop
      - staging
      - 'v[0-9].[0-9].[0-9]'
    paths-ignore: [ "docs/**", "data/**", "_templates/**" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16 ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: cd app && npm install
      - run: cd app && npm run lint
