Parameters:
  LMSDomainName:
    Description: The main domain name (ex - nichiboh.co.jp).
    Type: String
  LMSHostedZoneId:
    Description: The hosted zone id of LMSDomainName (e.g. Z2FDTNDATAQYW2)
    Type: String

Resources:
  LMSRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref LMSHostedZoneId
      RecordSets:
        # web
        - Name: !Sub app.${LMSDomainName}
          Type: A
          AliasTarget:
            DNSName: !GetAtt LMSCloudFrontDistributionWeb.DomainName
            EvaluateTargetHealth: True
            HostedZoneId: Z2FDTNDATAQYW2 # HostedZoneID of cloud front, value alway is Z2FDTNDATAQYW2, refer: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
        # api
        - Name: !Sub api.${LMSDomainName}
          Type: A
          AliasTarget:
            DNSName: !GetAtt LMSLoadBalancer.DNSName
            EvaluateTargetHealth: True
            HostedZoneId: !GetAtt LMSLoadBalancer.CanonicalHostedZoneID

Outputs:
  LMSWebDomainName:
    Value: !Sub app.${LMSDomainName}
  LMSApiDomainName:
    Value: !Sub api.${LMSDomainName}
